services:
  postgres:
    image: postgres:15-alpine
    container_name: hackathon_postgres
    environment:
      POSTGRES_DB: hackathon_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: hackathon_backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: hackathon_db
      DB_SSL_MODE: disable
      SERVER_PORT: 8080
      SERVER_HOST: 0.0.0.0
      ENV: development
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
